# ~/.config/starship.toml

# Disable the newline at the start of the prompt
add_newline = true
# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 30

[directory]
truncation_length	 = 8
truncate_to_repo = false

[nodejs]
disabled = true

[java]
disabled = true

[ruby]
disabled = true

[python]
disabled = true

[php]
disabeld = true

[gcloud]
disabled = true
