name: macos

on:
    push:
        branches:
            - master

jobs:
  macos-test:
    runs-on: macos-latest

    steps:
    - name: Run install.sh
      run: source /Users/runner/runners/2.263.0/work/dotfiles/install.sh
    
    - name: Run homebrew_install.sh
      run: source /Users/runner/runners/2.263.0/work/dotfiles/homebrew_install.sh
    
    - name: Load .zshrc
      run: zsh ~/.zshrc 2> error.log; cat error.log
           if [ -s error.log ]; then false; fi
